development:
  host: arqui1.ing.puc.cl
  port: 27030
  database: MovieManiacs

# set these environment variables on your prod server
production:
  host: arqui1.ing.puc.cl #<%= ENV['MONGOID_HOST'] %>
  port: 27030 #<%= ENV['MONGOID_PORT'] %>
  # username:  #<%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  database: MovieManiacs #<%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
